app.name=Poc Spring Boot
notification.enabled=true
notification.email.api-key=dev-email-key-123
notification.email.endpoint=http://localhost:2525
notification.sms.enabled=false
notification.slack.enabled=true
notification.slack.webhook=https://hooks.slack.com/dev/abc123
logging.level.com.lousing.poc=DEBUG